FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV PUBLIC_BACKEND_URL=http://localhost:5000

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
